# Generated by Django 5.0.4 on 2024-04-25 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppUsuario', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appusuarios',
            options={'verbose_name': 'Usuario', 'verbose_name_plural': 'Usuarios'},
        ),
        migrations.AddField(
            model_name='appusuarios',
            name='comuna',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Comuna'),
        ),
        migrations.AddField(
            model_name='appusuarios',
            name='direccion',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Direccion'),
        ),
    ]
